package compiler

import (
	_ "embed"
	"encoding/base64"
	"fmt"
	"html"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

//go:embed templates/dnd-style.css
var dndCSS string

//go:embed templates/act.md.tmpl
var actTemplate string

//go:embed templates/npc.md.tmpl
var npcTemplate string

//go:embed templates/monster.md.tmpl
var monsterTemplate string

//go:embed templates/encounter.md.tmpl
var encounterTemplate string

//go:embed templates/map.md.tmpl
var mapTemplate string

//go:embed templates/lore.md.tmpl
var loreTemplate string

type Compiler struct {
	CampaignDir string
	PDFEngine   string
}

func New(campaignDir, pdfEngine string) *Compiler {
	if pdfEngine == "" {
		pdfEngine = "wkhtmltopdf"
	}
	return &Compiler{
		CampaignDir: campaignDir,
		PDFEngine:   pdfEngine,
	}
}

func GetTemplate(tmplType string) (string, error) {
	switch tmplType {
	case "act":
		return actTemplate, nil
	case "npc":
		return npcTemplate, nil
	case "monster":
		return monsterTemplate, nil
	case "encounter":
		return encounterTemplate, nil
	case "map":
		return mapTemplate, nil
	case "lore":
		return loreTemplate, nil
	default:
		return "", fmt.Errorf("unknown template type: %s", tmplType)
	}
}

func (c *Compiler) Compile(title string) (string, error) {
	sections := []struct {
		name string
		path string
	}{
		{"README", filepath.Join(c.CampaignDir, "README.md")},
		{"Lore", filepath.Join(c.CampaignDir, "lore.md")},
		{"Acts", filepath.Join(c.CampaignDir, "acts")},
		{"NPCs", filepath.Join(c.CampaignDir, "npcs")},
		{"Bestiary", filepath.Join(c.CampaignDir, "bestiary")},
		{"Encounters", filepath.Join(c.CampaignDir, "encounters")},
		{"Maps", filepath.Join(c.CampaignDir, "maps")},
	}

	var htmlParts []string

	htmlParts = append(htmlParts, "<!DOCTYPE html>")
	htmlParts = append(htmlParts, "<html><head><meta charset='utf-8'>")
	htmlParts = append(htmlParts, "<style>"+dndCSS+"</style>")
	htmlParts = append(htmlParts, "</head><body>")
	htmlParts = append(htmlParts, fmt.Sprintf("<div class='cover'><h1>%s</h1><p class='subtitle'>Generated by Grimorio</p></div>", html.EscapeString(title)))
	htmlParts = append(htmlParts, "<div class='page-break'></div>")

	htmlParts = append(htmlParts, "<div class='toc'><h2>Table of Contents</h2><ul>")
	for _, sec := range sections {
		if _, err := os.Stat(sec.path); err == nil {
			htmlParts = append(htmlParts, fmt.Sprintf("<li>%s</li>", html.EscapeString(sec.name)))
		}
	}
	htmlParts = append(htmlParts, "</ul></div>")
	htmlParts = append(htmlParts, "<div class='page-break'></div>")

	for _, sec := range sections {
		info, err := os.Stat(sec.path)
		if err != nil {
			continue
		}

		if info.IsDir() {
			files, err := os.ReadDir(sec.path)
			if err != nil {
				continue
			}
			for _, f := range files {
				if strings.HasSuffix(f.Name(), ".md") {
					content, err := os.ReadFile(filepath.Join(sec.path, f.Name()))
					if err != nil {
						continue
					}
					htmlParts = append(htmlParts, markdownToHTML(string(content), c.CampaignDir))
					htmlParts = append(htmlParts, "<div class='page-break'></div>")
				}
			}
		} else {
			content, err := os.ReadFile(sec.path)
			if err != nil {
				continue
			}
			htmlParts = append(htmlParts, markdownToHTML(string(content), c.CampaignDir))
			htmlParts = append(htmlParts, "<div class='page-break'></div>")
		}
	}

	htmlParts = append(htmlParts, "</body></html>")

	htmlPath := filepath.Join(c.CampaignDir, "campaign.html")
	if err := os.WriteFile(htmlPath, []byte(strings.Join(htmlParts, "\n")), 0644); err != nil {
		return "", fmt.Errorf("failed to write HTML: %w", err)
	}

	pdfPath := filepath.Join(c.CampaignDir, "campaign.pdf")
	if err := c.htmlToPDF(htmlPath, pdfPath); err != nil {
		return "", fmt.Errorf("failed to convert to PDF: %w", err)
	}

	return pdfPath, nil
}

func (c *Compiler) htmlToPDF(htmlPath, pdfPath string) error {
	cmd := exec.Command(c.PDFEngine,
		"--enable-local-file-access",
		"--page-size", "A4",
		"--margin-top", "15mm",
		"--margin-bottom", "15mm",
		"--margin-left", "15mm",
		"--margin-right", "15mm",
		"--print-media-type",
		htmlPath,
		pdfPath,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("wkhtmltopdf failed: %w\nOutput: %s", err, string(output))
	}
	return nil
}

var (
	boldRegex   = regexp.MustCompile(`\*\*(.+?)\*\*`)
	italicRegex = regexp.MustCompile(`\*(.+?)\*`)
	imageRegex  = regexp.MustCompile(`!\[([^\]]*)\]\(([^)]+)\)`)
)

func markdownToHTML(md string, baseDir string) string {
	lines := strings.Split(md, "\n")
	var out []string
	inList := false
	var paragraphLines []string

	flushParagraph := func() {
		if len(paragraphLines) == 0 {
			return
		}
		text := strings.Join(paragraphLines, " ")
		paragraphLines = nil
		if text == "" {
			return
		}
		escaped := html.EscapeString(text)
		escaped = boldRegex.ReplaceAllString(escaped, "<strong>$1</strong>")
		escaped = italicRegex.ReplaceAllString(escaped, "<em>$1</em>")
		escaped = processImages(escaped, baseDir)
		out = append(out, fmt.Sprintf("<p>%s</p>", escaped))
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		if strings.HasPrefix(trimmed, "##### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "##### ")
			out = append(out, fmt.Sprintf("<h5>%s</h5>", html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "#### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "#### ")
			out = append(out, fmt.Sprintf("<h4>%s</h4>", html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "### ")
			out = append(out, fmt.Sprintf("<h3>%s</h3>", html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "## ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "## ")
			out = append(out, fmt.Sprintf("<h2>%s</h2>", html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "# ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "# ")
			out = append(out, fmt.Sprintf("<h1>%s</h1>", html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "- ") || strings.HasPrefix(trimmed, "* ") {
			flushParagraph()
			if !inList {
				out = append(out, "<ul>")
				inList = true
			}
			text := strings.TrimPrefix(trimmed, "- ")
			if strings.HasPrefix(trimmed, "* ") {
				text = strings.TrimPrefix(trimmed, "* ")
			}
			escaped := html.EscapeString(text)
			escaped = boldRegex.ReplaceAllString(escaped, "<strong>$1</strong>")
			escaped = italicRegex.ReplaceAllString(escaped, "<em>$1</em>")
			escaped = processImages(escaped, baseDir)
			out = append(out, fmt.Sprintf("<li>%s</li>", escaped))
		} else if trimmed == "" {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
		} else if imageRegex.MatchString(trimmed) {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			out = append(out, processImages(trimmed, baseDir))
		} else {
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			paragraphLines = append(paragraphLines, trimmed)
		}
	}

	flushParagraph()
	if inList {
		out = append(out, "</ul>")
	}

	return strings.Join(out, "\n")
}

func processImages(text string, baseDir string) string {
	return imageRegex.ReplaceAllStringFunc(text, func(match string) string {
		matches := imageRegex.FindStringSubmatch(match)
		if len(matches) < 3 {
			return match
		}
		alt := matches[1]
		imgPath := matches[2]

		if !filepath.IsAbs(imgPath) {
			imgPath = filepath.Join(baseDir, imgPath)
		}

		data, err := os.ReadFile(imgPath)
		if err != nil {
			return fmt.Sprintf(`<span class="image-missing">[Image: %s]</span>`, html.EscapeString(alt))
		}

		ext := strings.ToLower(filepath.Ext(imgPath))
		var mimeType string
		var content string

		switch ext {
		case ".svg":
			mimeType = "image/svg+xml"
			content = string(data)
			if !strings.Contains(content, "<svg") {
				return fmt.Sprintf(`<span class="image-missing">[Invalid SVG: %s]</span>`, html.EscapeString(alt))
			}
			return fmt.Sprintf(`<div class="campaign-image">%s</div>`, content)
		case ".png":
			mimeType = "image/png"
		case ".jpg", ".jpeg":
			mimeType = "image/jpeg"
		case ".gif":
			mimeType = "image/gif"
		case ".webp":
			mimeType = "image/webp"
		default:
			mimeType = "image/png"
		}

		encoded := base64.StdEncoding.EncodeToString(data)
		dataURI := fmt.Sprintf("data:%s;base64,%s", mimeType, encoded)
		return fmt.Sprintf(`<img src="%s" alt="%s" class="campaign-image"/>`, dataURI, html.EscapeString(alt))
	})
}
