package compiler

import (
	_ "embed"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

//go:embed templates/dnd-style.css
var dndCSS string

//go:embed templates/act.md.tmpl
var actTemplate string

//go:embed templates/npc.md.tmpl
var npcTemplate string

//go:embed templates/monster.md.tmpl
var monsterTemplate string

//go:embed templates/encounter.md.tmpl
var encounterTemplate string

//go:embed templates/map.md.tmpl
var mapTemplate string

//go:embed templates/lore.md.tmpl
var loreTemplate string

//go:embed templates/session-zero.md.tmpl
var sessionZeroTemplate string

type Compiler struct {
	CampaignDir     string
	PDFEngine       string
	CompilerVersion int
	seenImages      map[string]bool
}

func New(campaignDir, pdfEngine string) *Compiler {
	if pdfEngine == "" {
		pdfEngine = "wkhtmltopdf"
	}
	return &Compiler{
		CampaignDir:     campaignDir,
		PDFEngine:       pdfEngine,
		CompilerVersion: 2,
		seenImages:      make(map[string]bool),
	}
}

// NewWithVersion creates a compiler with a specific version (1 or 2)
func NewWithVersion(campaignDir, pdfEngine string, version int) *Compiler {
	c := New(campaignDir, pdfEngine)
	if version == 1 || version == 2 {
		c.CompilerVersion = version
	}
	return c
}

func GetTemplate(tmplType string) (string, error) {
	switch tmplType {
	case "act":
		return actTemplate, nil
	case "npc":
		return npcTemplate, nil
	case "monster":
		return monsterTemplate, nil
	case "encounter":
		return encounterTemplate, nil
	case "map":
		return mapTemplate, nil
	case "lore":
		return loreTemplate, nil
	case "session-zero":
		return sessionZeroTemplate, nil
	default:
		return "", fmt.Errorf("unknown template type: %s", tmplType)
	}
}

func (c *Compiler) Compile(title string) (string, error) {
	htmlParts, err := c.generateHTML(title)
	if err != nil {
		return "", err
	}

	htmlPath := filepath.Join(c.CampaignDir, "campaign.html")
	if err := os.WriteFile(htmlPath, []byte(strings.Join(htmlParts, "\n")), 0644); err != nil {
		return "", fmt.Errorf("failed to write HTML: %w", err)
	}

	pdfPath := filepath.Join(c.CampaignDir, "campaign.pdf")

	// Retry loop: verify images after PDF generation and retry if missing
	maxRetries := 3
	var lastExpected, lastFound int
	for attempt := 0; attempt < maxRetries; attempt++ {
		if err := c.htmlToPDF(htmlPath, pdfPath); err != nil {
			return "", fmt.Errorf("failed to convert to PDF (attempt %d): %w", attempt+1, err)
		}

		// Verify images are present in the generated HTML
		expected, found, ok, err := c.verifyImages(htmlPath)
		if err != nil {
			return "", fmt.Errorf("failed to verify images (attempt %d): %w", attempt+1, err)
		}
		lastExpected = expected
		lastFound = found
		if ok {
			return pdfPath, nil
		}

		if attempt < maxRetries-1 {
			// Regenerate HTML (images might need re-embedding)
			// Clear seen images to allow re-embedding
			c.seenImages = make(map[string]bool)
			// Re-read source files and regenerate HTML
			htmlParts, err = c.generateHTML(title)
			if err != nil {
				return "", fmt.Errorf("failed to regenerate HTML (attempt %d): %w", attempt+1, err)
			}
			if err := os.WriteFile(htmlPath, []byte(strings.Join(htmlParts, "\n")), 0644); err != nil {
				return "", fmt.Errorf("failed to write regenerated HTML (attempt %d): %w", attempt+1, err)
			}
		}
	}

	return "", fmt.Errorf("PDF generation failed after %d attempts: images missing (expected %d, found %d)", maxRetries, lastExpected, lastFound)
}

// generateHTML reads all markdown sources and generates the full HTML document.
func (c *Compiler) generateHTML(title string) ([]string, error) {
	sections := []struct {
		name  string
		path  string
		isDir bool
	}{
		{"Lore y Ambientación", filepath.Join(c.CampaignDir, "lore.md"), false},
		{"Acts", filepath.Join(c.CampaignDir, "acts"), true},
		{"Apéndice A: NPCs y Facciones", filepath.Join(c.CampaignDir, "npcs"), true},
		{"Apéndice B: Bestiario", filepath.Join(c.CampaignDir, "bestiary"), true},
		{"Apéndice C: Encuentros", filepath.Join(c.CampaignDir, "encounters"), true},
		{"Apéndice D: Mapas de Referencia", filepath.Join(c.CampaignDir, "maps"), true},
	}

	var htmlParts []string
	headingCounter := 0

	htmlParts = append(htmlParts, "<!DOCTYPE html>")
	htmlParts = append(htmlParts, "<html><head><meta charset='utf-8'>")
	htmlParts = append(htmlParts, "<style>"+dndCSS+"</style>")
	htmlParts = append(htmlParts, "</head><body>")

	// Cover page — single page, no split
	htmlParts = append(htmlParts, fmt.Sprintf(`<div class="cover-wrapper" id="cover"><h1>%s</h1><p class="subtitle">Generated by Grimorio</p>`, html.EscapeString(title)))

	// Insert cover art if exists — search for cover.* or cover-*.*
	coverPath := findCoverImage(c.CampaignDir)
	if coverPath != "" {
		htmlParts = append(htmlParts, fmt.Sprintf(`<div class="cover-image">%s</div>`, embedImage(coverPath, "Cover Art", c.CampaignDir, c.seenImages)))
	}

	htmlParts = append(htmlParts, `</div>`)

	// Session Zero guidance (if available)
	sessionZeroHTML := c.generateSessionZero()
	if sessionZeroHTML != "" {
		htmlParts = append(htmlParts, `<div class="section-break"></div>`)
		htmlParts = append(htmlParts, sessionZeroHTML)
		htmlParts = append(htmlParts, `<div class="section-break"></div>`)
	}

	// Flowchart SVG (if available)
	flowchartHTML := c.generateFlowchartEmbed()
	if flowchartHTML != "" {
		htmlParts = append(htmlParts, flowchartHTML)
		htmlParts = append(htmlParts, `<div class="section-break"></div>`)
	}

	// TOC
	htmlParts = append(htmlParts, `<div class="toc" id="toc"><h2>Table of Contents</h2><ul>`)
	for _, sec := range sections {
		if _, err := os.Stat(sec.path); err == nil {
			id := "sec-" + sanitizeID(sec.name)
			htmlParts = append(htmlParts, fmt.Sprintf(`<li><a href="#%s">%s</a><span class="page-ref"></span></li>`, id, html.EscapeString(sec.name)))
		}
	}
	htmlParts = append(htmlParts, `</ul></div>`)
	htmlParts = append(htmlParts, `<div class="section-break"></div>`)

	for _, sec := range sections {
		if _, err := os.Stat(sec.path); err != nil {
			continue
		}

		if sec.isDir {
			files, err := os.ReadDir(sec.path)
			if err != nil {
				continue
			}
			hasContent := false
			for _, f := range files {
				if strings.HasSuffix(f.Name(), ".md") {
					content, err := os.ReadFile(filepath.Join(sec.path, f.Name()))
					if err != nil {
						continue
					}
					sectionID := "sec-" + sanitizeID(sec.name+"-"+f.Name())
					htmlResult := markdownToHTMLWithID(string(content), c.CampaignDir, sectionID, &headingCounter, c.seenImages)
					if strings.TrimSpace(htmlResult) != "" {
						htmlParts = append(htmlParts, htmlResult)
						hasContent = true
					}
				}
			}
			if hasContent {
				htmlParts = append(htmlParts, `<div class="section-break"></div>`)
			}
		} else {
			content, err := os.ReadFile(sec.path)
			if err != nil {
				continue
			}
			sectionID := "sec-" + sanitizeID(sec.name)
			htmlResult := markdownToHTMLWithID(string(content), c.CampaignDir, sectionID, &headingCounter, c.seenImages)
			if strings.TrimSpace(htmlResult) != "" {
				htmlParts = append(htmlParts, htmlResult)
			}
			htmlParts = append(htmlParts, `<div class="section-break"></div>`)
		}
	}

	// Apéndice E: Faction Tracker
	trackerHTML := c.generateFactionTracker()
	if trackerHTML != "" {
		htmlParts = append(htmlParts, `<div class="section-break"></div>`)
		htmlParts = append(htmlParts, trackerHTML)
	}

	// Apéndice F: Adventure Roster
	rosterHTML := c.generateAdventureRoster()
	if rosterHTML != "" {
		htmlParts = append(htmlParts, `<div class="section-break"></div>`)
		htmlParts = append(htmlParts, rosterHTML)
	}

	htmlParts = append(htmlParts, "</body></html>")
	return htmlParts, nil
}

// generateFactionTracker reads the reputation matrix and generates an HTML appendix.
func (c *Compiler) generateFactionTracker() string {
	matrixPath := filepath.Join(c.CampaignDir, "factions", "reputation_matrix.json")
	data, err := os.ReadFile(matrixPath)
	if err != nil {
		return "" // no factions, no tracker
	}

	var matrix struct {
		CampaignID string `json:"campaign_id"`
		Entries    []struct {
			FactionID string `json:"faction_id"`
			PartyID   string `json:"party_id"`
			Score     int8   `json:"score"`
			Status    string `json:"status"`
		} `json:"entries"`
	}
	if err := json.Unmarshal(data, &matrix); err != nil {
		return ""
	}
	if len(matrix.Entries) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(`<h2 id="sec-faction-tracker">Apéndice E: Faction Tracker</h2>`)
	b.WriteString(`<table><thead><tr><th>Faction</th><th>Party</th><th>Score</th><th>Status</th></tr></thead><tbody>`)
	for _, e := range matrix.Entries {
		statusClass := "status-" + strings.ToLower(e.Status)
		b.WriteString(fmt.Sprintf(`<tr class="%s"><td>%s</td><td>%s</td><td>%d</td><td>%s</td></tr>`,
			statusClass, html.EscapeString(e.FactionID), html.EscapeString(e.PartyID), e.Score, html.EscapeString(e.Status)))
	}
	b.WriteString(`</tbody></table>`)
	return b.String()
}

// generateSessionZero reads session-zero.md and converts to HTML
func (c *Compiler) generateSessionZero() string {
	path := filepath.Join(c.CampaignDir, "session-zero.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return "" // no session zero, skip
	}

	htmlResult := markdownToHTMLWithID(string(data), c.CampaignDir, "sec-session-zero", new(int), c.seenImages)
	if strings.TrimSpace(htmlResult) == "" {
		return ""
	}

	return `<h2 id="sec-session-zero">Sesión Cero — Guía para el DM</h2>` + htmlResult
}

// generateFlowchartEmbed embeds the flowchart SVG if available
func (c *Compiler) generateFlowchartEmbed() string {
	path := filepath.Join(c.CampaignDir, "flowchart.svg")
	data, err := os.ReadFile(path)
	if err != nil {
		return "" // no flowchart, skip
	}

	return fmt.Sprintf(`<h2 id="sec-flowchart">Campaign Flowchart</h2><div class="flowchart">%s</div>`, string(data))
}

// generateAdventureRoster builds Apéndice F from scanned markdown files
func (c *Compiler) generateAdventureRoster() string {
	var npcs, monsters, encounters []string

	// Scan acts for entities
	actsDir := filepath.Join(c.CampaignDir, "acts")
	if info, err := os.Stat(actsDir); err == nil && info.IsDir() {
		files, _ := os.ReadDir(actsDir)
		for _, f := range files {
			if strings.HasSuffix(f.Name(), ".md") {
				content, _ := os.ReadFile(filepath.Join(actsDir, f.Name()))
				n, m, e := extractRosterEntries(string(content))
				npcs = append(npcs, n...)
				monsters = append(monsters, m...)
				encounters = append(encounters, e...)
			}
		}
	}

	// Scan npcs dir
	npcsDir := filepath.Join(c.CampaignDir, "npcs")
	if info, err := os.Stat(npcsDir); err == nil && info.IsDir() {
		files, _ := os.ReadDir(npcsDir)
		for _, f := range files {
			if strings.HasSuffix(f.Name(), ".md") {
				content, _ := os.ReadFile(filepath.Join(npcsDir, f.Name()))
				n, _, _ := extractRosterEntries(string(content))
				npcs = append(npcs, n...)
			}
		}
	}

	// Scan bestiary
	bestiaryDir := filepath.Join(c.CampaignDir, "bestiary")
	if info, err := os.Stat(bestiaryDir); err == nil && info.IsDir() {
		files, _ := os.ReadDir(bestiaryDir)
		for _, f := range files {
			if strings.HasSuffix(f.Name(), ".md") {
				content, _ := os.ReadFile(filepath.Join(bestiaryDir, f.Name()))
				_, m, _ := extractRosterEntries(string(content))
				monsters = append(monsters, m...)
			}
		}
	}

	// Scan encounters
	encountersDir := filepath.Join(c.CampaignDir, "encounters")
	if info, err := os.Stat(encountersDir); err == nil && info.IsDir() {
		files, _ := os.ReadDir(encountersDir)
		for _, f := range files {
			if strings.HasSuffix(f.Name(), ".md") {
				content, _ := os.ReadFile(filepath.Join(encountersDir, f.Name()))
				_, _, e := extractRosterEntries(string(content))
				encounters = append(encounters, e...)
			}
		}
	}

	if len(npcs) == 0 && len(monsters) == 0 && len(encounters) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(`<h2 id="sec-adventure-roster">Apéndice F: Adventure Roster</h2>`)

	if len(npcs) > 0 {
		b.WriteString(`<h3>NPCs</h3><table><thead><tr><th>Nombre</th><th>Rol</th></tr></thead><tbody>`)
		for _, n := range npcs {
			parts := strings.SplitN(n, "|", 2)
			name := parts[0]
			role := ""
			if len(parts) > 1 {
				role = parts[1]
			}
			b.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td></tr>`, html.EscapeString(name), html.EscapeString(role)))
		}
		b.WriteString(`</tbody></table>`)
	}

	if len(monsters) > 0 {
		b.WriteString(`<h3>Monstruos</h3><table><thead><tr><th>Nombre</th><th>CR</th></tr></thead><tbody>`)
		for _, m := range monsters {
			parts := strings.SplitN(m, "|", 2)
			name := parts[0]
			cr := ""
			if len(parts) > 1 {
				cr = parts[1]
			}
			b.WriteString(fmt.Sprintf(`<tr><td>%s</td><td>%s</td></tr>`, html.EscapeString(name), html.EscapeString(cr)))
		}
		b.WriteString(`</tbody></table>`)
	}

	if len(encounters) > 0 {
		b.WriteString(`<h3>Encuentros</h3><table><thead><tr><th>Nombre</th></tr></thead><tbody>`)
		for _, e := range encounters {
			b.WriteString(fmt.Sprintf(`<tr><td>%s</td></tr>`, html.EscapeString(e)))
		}
		b.WriteString(`</tbody></table>`)
	}

	return b.String()
}

// extractRosterEntries parses markdown for roster entities
func extractRosterEntries(md string) (npcs, monsters, encounters []string) {
	lines := strings.Split(md, "\n")
	var inNPCs, inMonsters, inEncounters bool
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		lower := strings.ToLower(trimmed)

		if strings.HasPrefix(lower, "## ") || strings.HasPrefix(lower, "### ") {
			inNPCs = strings.Contains(lower, "npc") || strings.Contains(lower, "personaje")
			inMonsters = strings.Contains(lower, "monstruo") || strings.Contains(lower, "criatura") || strings.Contains(lower, "bestia")
			inEncounters = strings.Contains(lower, "encuentro")
			continue
		}

		if strings.HasPrefix(trimmed, "- ") || strings.HasPrefix(trimmed, "* ") {
			item := strings.TrimPrefix(trimmed, "- ")
			if strings.HasPrefix(trimmed, "* ") {
				item = strings.TrimPrefix(trimmed, "* ")
			}
			item = strings.TrimSpace(item)
			// Extract bold name
			if m := boldRegex.FindStringSubmatch(item); m != nil {
				name := m[1]
				rest := strings.TrimSpace(strings.TrimPrefix(item, m[0]))
				rest = strings.TrimPrefix(rest, "—")
				rest = strings.TrimPrefix(rest, "-")
				rest = strings.TrimSpace(rest)
				if inNPCs {
					npcs = append(npcs, name+"|"+rest)
				} else if inMonsters {
					monsters = append(monsters, name+"|"+rest)
				} else if inEncounters {
					encounters = append(encounters, name)
				}
			} else if inEncounters && item != "" {
				encounters = append(encounters, item)
			}
		}
	}
	return
}

// verifyImages compares the number of expected images in markdown sources
// with the number of <img> tags in the generated HTML.
// Returns (expected, found, ok, error).
func (c *Compiler) verifyImages(htmlPath string) (int, int, bool, error) {
	expected, err := c.countImagesInMarkdownSources()
	if err != nil {
		return 0, 0, false, err
	}

	found, err := countImagesInHTML(htmlPath)
	if err != nil {
		return expected, 0, false, err
	}

	// ok if found >= expected (some images might be deduplicated)
	return expected, found, found >= expected, nil
}

// countImagesInMarkdownSources walks all markdown files in the campaign directory
// and counts image references: markdown ![alt](path), <img> tags, and `assets/file` refs.
func (c *Compiler) countImagesInMarkdownSources() (int, error) {
	count := 0

	sections := []string{
		filepath.Join(c.CampaignDir, "lore.md"),
		filepath.Join(c.CampaignDir, "acts"),
		filepath.Join(c.CampaignDir, "npcs"),
		filepath.Join(c.CampaignDir, "bestiary"),
		filepath.Join(c.CampaignDir, "encounters"),
		filepath.Join(c.CampaignDir, "maps"),
	}

	for _, secPath := range sections {
		info, err := os.Stat(secPath)
		if err != nil {
			continue
		}

		if info.IsDir() {
			files, err := os.ReadDir(secPath)
			if err != nil {
				continue
			}
			for _, f := range files {
				if strings.HasSuffix(f.Name(), ".md") {
					content, err := os.ReadFile(filepath.Join(secPath, f.Name()))
					if err != nil {
						continue
					}
					count += countImagesInMarkdown(string(content))
				}
			}
		} else {
			content, err := os.ReadFile(secPath)
			if err != nil {
				continue
			}
			count += countImagesInMarkdown(string(content))
		}
	}

	return count, nil
}

// countImagesInMarkdown counts image references in a single markdown string.
func countImagesInMarkdown(md string) int {
	count := 0
	// Count markdown images: ![alt](path)
	count += len(imageRegex.FindAllString(md, -1))
	// Count raw <img> tags
	count += len(imgTagRegex.FindAllString(md, -1))
	// Count code asset refs: `assets/filename.ext`
	count += len(codeAssetRegex.FindAllString(md, -1))
	return count
}

// countImagesInHTML counts <img> tags in the generated HTML file.
func countImagesInHTML(htmlPath string) (int, error) {
	content, err := os.ReadFile(htmlPath)
	if err != nil {
		return 0, err
	}
	return len(imgTagRegex.FindAllString(string(content), -1)), nil
}

func sanitizeID(s string) string {
	result := []rune(s)
	for i, r := range result {
		if (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9') {
			result[i] = '-'
		}
	}
	return strings.ToLower(string(result))
}

func (c *Compiler) htmlToPDF(htmlPath, pdfPath string) error {
	cmd := exec.Command(c.PDFEngine,
		"--enable-local-file-access",
		"--page-size", "A4",
		"--margin-top", "15mm",
		"--margin-bottom", "15mm",
		"--margin-left", "15mm",
		"--margin-right", "15mm",
		"--print-media-type",
		"--footer-center", "[page]/[topage]",
		"--footer-font-size", "8",
		htmlPath,
		pdfPath,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("wkhtmltopdf failed: %w\nOutput: %s", err, string(output))
	}
	return nil
}

var (
	boldRegex         = regexp.MustCompile(`\*\*(.+?)\*\*`)
	italicRegex       = regexp.MustCompile(`\*(.+?)\*`)
	boldAdjacentRegex = regexp.MustCompile(`</strong>([^\s<])`)
	imageRegex        = regexp.MustCompile(`!\[([^\]]*)\]\(([^)]+)\)`)
	imgTagRegex       = regexp.MustCompile(`<img[^>]*(?:/\s*)?>`)

	blockquoteRe   = regexp.MustCompile(`^>\s*(.*)`)
	codeAssetRegex = regexp.MustCompile("`assets/([\\w\\-]+\\.(svg|png|jpg|jpeg|gif|webp))`")
	sceneRegex     = regexp.MustCompile(`\[SCENE:\s*(.*?)\]`)
)

// formatInline processes bold and italic markers, ensuring no word merging after </strong>
func formatInline(text string) string {
	text = boldRegex.ReplaceAllString(text, "<strong>$1</strong>")
	text = boldAdjacentRegex.ReplaceAllString(text, "</strong>\u0026thinsp;$1")
	return italicRegex.ReplaceAllString(text, "<em>$1</em>")
}

// processInlineText processes markdown images, escapes HTML, formats inline,
// and preserves existing <img> tags so they are not escaped.
func processInlineText(text string, baseDir string, seenImages map[string]bool) string {
	// 1. Process markdown images first
	text = processImages(text, baseDir, seenImages)

	// 2. Extract and preserve existing <img> tags
	var imgTags []string
	text = imgTagRegex.ReplaceAllStringFunc(text, func(match string) string {
		imgTags = append(imgTags, match)
		return "\x00IMG\x00"
	})

	// 3. Escape HTML
	text = html.EscapeString(text)

	// 4. Format inline (bold, italic)
	text = formatInline(text)

	// 5. Restore <img> tags
	for _, img := range imgTags {
		text = strings.Replace(text, "\x00IMG\x00", img, 1)
	}

	return text
}

func markdownToHTMLWithID(md string, baseDir string, sectionID string, headingCounter *int, seenImages map[string]bool) string {
	lines := strings.Split(md, "\n")
	var out []string
	inList := false
	var paragraphLines []string

	// Table state
	inTable := false
	var tableRows []string
	var pendingTableRow string // buffered row waiting for separator confirmation

	// Blockquote state (read-aloud)
	inBlockquote := false
	var blockquoteLines []string

	// Code block state
	inCodeBlock := false
	var codeBlockLines []string

	flushCodeBlock := func() {
		if len(codeBlockLines) == 0 {
			return
		}
		code := strings.Join(codeBlockLines, "\n")
		codeBlockLines = nil
		if code == "" {
			return
		}
		escaped := html.EscapeString(code)
		out = append(out, fmt.Sprintf(`<pre class="code-block"><code>%s</code></pre>`, escaped))
	}

	flushBlockquote := func() {
		if len(blockquoteLines) == 0 {
			return
		}
		text := strings.Join(blockquoteLines, " ")
		blockquoteLines = nil
		if text == "" {
			return
		}
		escaped := processInlineText(text, baseDir, seenImages)
		out = append(out, fmt.Sprintf(`<div class="read-aloud">%s</div>`, escaped))
	}

	flushParagraph := func() {
		if len(paragraphLines) == 0 {
			return
		}
		text := strings.Join(paragraphLines, " ")
		paragraphLines = nil
		if text == "" {
			return
		}
		escaped := processInlineText(text, baseDir, seenImages)
		out = append(out, fmt.Sprintf("<p>%s</p>", escaped))
	}

	flushTable := func() {
		if len(tableRows) < 2 {
			// Not a valid table, treat rows as paragraphs
			for _, row := range tableRows {
				if strings.TrimSpace(row) != "" {
					escaped := processInlineText(strings.TrimSpace(row), baseDir, seenImages)
					out = append(out, fmt.Sprintf("<p>%s</p>", escaped))
				}
			}
			tableRows = nil
			return
		}
		headers := parseTableRow(tableRows[0])
		alignments := parseTableAlign(tableRows[1])
		var htmlOut strings.Builder
		htmlOut.WriteString(`<table><thead><tr>`)
		for i, h := range headers {
			align := ""
			if i < len(alignments) {
				align = alignments[i]
			}
			if align != "" {
				htmlOut.WriteString(fmt.Sprintf(`<th style="text-align:%s">%s</th>`, align, h))
			} else {
				htmlOut.WriteString(fmt.Sprintf(`<th>%s</th>`, h))
			}
		}
		htmlOut.WriteString(`</tr></thead><tbody>`)
		for _, row := range tableRows[2:] {
			cells := parseTableRow(row)
			htmlOut.WriteString(`<tr>`)
			for i, cell := range cells {
				align := ""
				if i < len(alignments) {
					align = alignments[i]
				}
				cellEsc := processInlineText(cell, baseDir, seenImages)
				if align != "" {
					htmlOut.WriteString(fmt.Sprintf(`<td style="text-align:%s">%s</td>`, align, cellEsc))
				} else {
					htmlOut.WriteString(fmt.Sprintf(`<td>%s</td>`, cellEsc))
				}
			}
			htmlOut.WriteString(`</tr>`)
		}
		htmlOut.WriteString(`</tbody></table>`)
		out = append(out, htmlOut.String())
		tableRows = nil
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip horizontal rules (---, ***, ___, - - -)
		if trimmed == "---" || trimmed == "***" || trimmed == "___" || trimmed == "- - -" {
			continue
		}

		// Skip empty lines inside table
		if inTable && trimmed == "" {
			continue
		}

		// Handle scene placeholders [SCENE: description]
		if sceneMatch := sceneRegex.FindStringSubmatch(trimmed); sceneMatch != nil {
			flushParagraph()
			flushBlockquote()
			flushTable()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			sceneDesc := sceneMatch[1]
			escaped := html.EscapeString(sceneDesc)
			escaped = formatInline(escaped)
			out = append(out, fmt.Sprintf(`<div class="scene-description">🎭 %s</div>`, escaped))
			continue
		}

		// If we have a pending row and current line is a separator, start table
		if pendingTableRow != "" && isTableSeparator(trimmed) {
			inTable = true
			tableRows = append(tableRows, pendingTableRow)
			tableRows = append(tableRows, trimmed)
			pendingTableRow = ""
			continue
		}

		// If we have a pending row but current line is NOT a separator, flush pending as paragraph
		if pendingTableRow != "" && !isTableRow(trimmed) {
			paragraphLines = append(paragraphLines, pendingTableRow)
			pendingTableRow = ""
		}

		// If we're in a table and see another row, add it
		if inTable && isTableRow(trimmed) {
			tableRows = append(tableRows, trimmed)
			continue
		}

		// If we were in a table but now see non-table content, flush table
		if inTable {
			flushTable()
			inTable = false
		}

		// If line looks like a table row, buffer it (might be table start)
		if isTableRow(trimmed) && !inTable {
			pendingTableRow = trimmed
			continue
		}

		// Handle code blocks (```)
		if strings.HasPrefix(trimmed, "```") {
			if inCodeBlock {
				// End code block
				flushCodeBlock()
				inCodeBlock = false
			} else {
				// Start code block
				flushParagraph()
				flushBlockquote()
				if inList {
					out = append(out, "</ul>")
					inList = false
				}
				inCodeBlock = true
			}
			continue
		}

		// If we're inside a code block, collect lines
		if inCodeBlock {
			codeBlockLines = append(codeBlockLines, line) // Keep original line, not trimmed
			continue
		}

		// Handle blockquotes (read-aloud text)
		if bqMatch := blockquoteRe.FindStringSubmatch(trimmed); bqMatch != nil {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			inBlockquote = true
			blockquoteLines = append(blockquoteLines, bqMatch[1])
			continue
		}

		// If we were in a blockquote but now see non-blockquote content, flush it
		if inBlockquote {
			flushBlockquote()
			inBlockquote = false
		}

		// Handle headings
		if strings.HasPrefix(trimmed, "##### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "##### ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h5 id="%s">%s</h5>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "#### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "#### ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h4 id="%s">%s</h4>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "### ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h3 id="%s">%s</h3>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "## ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "## ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h2 id="%s">%s</h2>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "# ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "# ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h1 id="%s">%s</h1>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "- ") || strings.HasPrefix(trimmed, "* ") {
			flushParagraph()
			if !inList {
				out = append(out, "<ul>")
				inList = true
			}
			text := strings.TrimPrefix(trimmed, "- ")
			if strings.HasPrefix(trimmed, "* ") {
				text = strings.TrimPrefix(trimmed, "* ")
			}
			escaped := processInlineText(text, baseDir, seenImages)
			out = append(out, fmt.Sprintf("<li>%s</li>", escaped))
		} else if trimmed == "" {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
		} else if imageRegex.MatchString(trimmed) {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			out = append(out, processImages(trimmed, baseDir, seenImages))
		} else {
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			paragraphLines = append(paragraphLines, trimmed)
		}
	}

	flushParagraph()
	flushTable()
	flushBlockquote()
	flushCodeBlock()
	if inList {
		out = append(out, "</ul>")
	}

	return strings.Join(out, "\n")
}

func isTableRow(line string) bool {
	return strings.HasPrefix(line, "|") && strings.HasSuffix(line, "|") && strings.Count(line, "|") >= 3
}

func isTableSeparator(line string) bool {
	if !isTableRow(line) {
		return false
	}
	inner := strings.Trim(line, "|")
	parts := strings.Split(inner, "|")
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if p[0] != '-' && p[0] != ':' {
			return false
		}
	}
	return true
}

func parseTableRow(row string) []string {
	row = strings.TrimSpace(row)
	row = strings.TrimPrefix(row, "|")
	row = strings.TrimSuffix(row, "|")
	parts := strings.Split(row, "|")
	var result []string
	for _, p := range parts {
		result = append(result, strings.TrimSpace(p))
	}
	return result
}

func parseTableAlign(row string) []string {
	cells := parseTableRow(row)
	var alignments []string
	for _, cell := range cells {
		cell = strings.TrimSpace(cell)
		leftDash := strings.HasPrefix(cell, ":")
		rightDash := strings.HasSuffix(cell, ":")
		if leftDash && rightDash {
			alignments = append(alignments, "center")
		} else if rightDash {
			alignments = append(alignments, "right")
		} else {
			alignments = append(alignments, "left")
		}
	}
	return alignments
}

func markdownToHTML(md string, baseDir string) string {
	counter := 0
	seen := make(map[string]bool)
	return markdownToHTMLWithID(md, baseDir, "content", &counter, seen)
}

func processImages(text string, baseDir string, seenImages map[string]bool) string {
	text = imageRegex.ReplaceAllStringFunc(text, func(match string) string {
		matches := imageRegex.FindStringSubmatch(match)
		if len(matches) < 3 {
			return match
		}
		alt := matches[1]
		imgPath := matches[2]

		if !filepath.IsAbs(imgPath) {
			// Strip ../ and ./ prefixes — assets are always under campaign root
			for strings.HasPrefix(imgPath, "../") {
				imgPath = strings.TrimPrefix(imgPath, "../")
			}
			for strings.HasPrefix(imgPath, "./") {
				imgPath = strings.TrimPrefix(imgPath, "./")
			}
			imgPath = filepath.Join(baseDir, imgPath)
		}

		return embedImage(imgPath, alt, baseDir, seenImages)
	})

	// Detect code-formatted asset refs: `assets/filename.ext`
	text = codeAssetRegex.ReplaceAllStringFunc(text, func(match string) string {
		matches := codeAssetRegex.FindStringSubmatch(match)
		if len(matches) < 2 {
			return match
		}
		filename := matches[1]
		imgPath := filepath.Join(baseDir, "assets", filename)
		return embedImage(imgPath, filename, baseDir, seenImages)
	})

	return text
}

func embedImage(imgPath, alt, baseDir string, seenImages map[string]bool) string {
	// Deduplicate: skip if same image path already embedded
	if seenImages[imgPath] {
		return ""
	}
	seenImages[imgPath] = true

	data, err := os.ReadFile(imgPath)
	if err != nil {
		return fmt.Sprintf(`<span class="image-missing">[Image: %s]</span>`, html.EscapeString(alt))
	}

	ext := strings.ToLower(filepath.Ext(imgPath))
	var mimeType string

	switch ext {
	case ".svg":
		// Use SVG directly - wkhtmltopdf can render SVG files with --enable-local-file-access
		// Return relative path from campaign directory
		relPath, _ := filepath.Rel(baseDir, imgPath)
		if relPath == "" {
			relPath = imgPath
		}
		return fmt.Sprintf(`<img src="%s" alt="%s" class="campaign-image"/>`, html.EscapeString(relPath), html.EscapeString(alt))
	case ".png":
		mimeType = "image/png"
	case ".jpg", ".jpeg":
		mimeType = "image/jpeg"
	case ".gif":
		mimeType = "image/gif"
	case ".webp":
		mimeType = "image/webp"
	default:
		mimeType = "image/png"
	}

	encoded := base64.StdEncoding.EncodeToString(data)
	dataURI := fmt.Sprintf("data:%s;base64,%s", mimeType, encoded)
	return fmt.Sprintf(`<img src="%s" alt="%s" class="campaign-image"/>`, dataURI, html.EscapeString(alt))
}

// findCoverImage searches for a cover image in the campaign's assets directory.
// Priority: cover.ext > cover-*.ext (tries png, jpg, jpeg, webp, svg in order)
func findCoverImage(campaignDir string) string {
	extensions := []string{".png", ".jpg", ".jpeg", ".webp", ".svg"}
	baseDir := filepath.Join(campaignDir, "assets")

	for _, ext := range extensions {
		if covers, _ := filepath.Glob(filepath.Join(baseDir, "cover"+ext)); len(covers) > 0 {
			return covers[0]
		}
	}
	for _, ext := range extensions {
		if covers, _ := filepath.Glob(filepath.Join(baseDir, "cover-*"+ext)); len(covers) > 0 {
			return covers[0]
		}
	}
	return ""
}
