package compiler

import (
	_ "embed"
	"encoding/base64"
	"fmt"
	"html"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

//go:embed templates/dnd-style.css
var dndCSS string

//go:embed templates/act.md.tmpl
var actTemplate string

//go:embed templates/npc.md.tmpl
var npcTemplate string

//go:embed templates/monster.md.tmpl
var monsterTemplate string

//go:embed templates/encounter.md.tmpl
var encounterTemplate string

//go:embed templates/map.md.tmpl
var mapTemplate string

//go:embed templates/lore.md.tmpl
var loreTemplate string

type Compiler struct {
	CampaignDir string
	PDFEngine   string
	seenImages  map[string]bool
}

func New(campaignDir, pdfEngine string) *Compiler {
	if pdfEngine == "" {
		pdfEngine = "wkhtmltopdf"
	}
	return &Compiler{
		CampaignDir: campaignDir,
		PDFEngine:   pdfEngine,
		seenImages:  make(map[string]bool),
	}
}

func GetTemplate(tmplType string) (string, error) {
	switch tmplType {
	case "act":
		return actTemplate, nil
	case "npc":
		return npcTemplate, nil
	case "monster":
		return monsterTemplate, nil
	case "encounter":
		return encounterTemplate, nil
	case "map":
		return mapTemplate, nil
	case "lore":
		return loreTemplate, nil
	default:
		return "", fmt.Errorf("unknown template type: %s", tmplType)
	}
}

type tocEntry struct {
	name string
	id   string
}

func (c *Compiler) Compile(title string) (string, error) {
	sections := []struct {
		name  string
		path  string
		isDir bool
	}{
		{"Lore y Ambientación", filepath.Join(c.CampaignDir, "lore.md"), false},
		{"Acts", filepath.Join(c.CampaignDir, "acts"), true},
		{"Apéndice A: NPCs y Facciones", filepath.Join(c.CampaignDir, "npcs"), true},
		{"Apéndice B: Bestiario", filepath.Join(c.CampaignDir, "bestiary"), true},
		{"Apéndice C: Encuentros", filepath.Join(c.CampaignDir, "encounters"), true},
		{"Apéndice D: Mapas de Referencia", filepath.Join(c.CampaignDir, "maps"), true},
	}

	var htmlParts []string
	headingCounter := 0

	htmlParts = append(htmlParts, "<!DOCTYPE html>")
	htmlParts = append(htmlParts, "<html><head><meta charset='utf-8'>")
	htmlParts = append(htmlParts, "<style>"+dndCSS+"</style>")
	htmlParts = append(htmlParts, "</head><body>")

	// Cover page — single page, no split
	htmlParts = append(htmlParts, fmt.Sprintf(`<div class="cover-wrapper" id="cover"><h1>%s</h1><p class="subtitle">Generated by Grimorio</p>`, html.EscapeString(title)))
	
	// Insert cover art if exists — search for any cover-*.png
	covers, _ := filepath.Glob(filepath.Join(c.CampaignDir, "assets", "cover-*.png"))
	if len(covers) > 0 {
		coverPath := covers[0]
		htmlParts = append(htmlParts, fmt.Sprintf(`<div class="cover-image">%s</div>`, embedImage(coverPath, "Cover Art", c.CampaignDir, c.seenImages)))
	}
	
	htmlParts = append(htmlParts, `</div>`)

	// TOC
	htmlParts = append(htmlParts, `<div class="toc" id="toc"><h2>Table of Contents</h2><ul>`)
	for _, sec := range sections {
		if _, err := os.Stat(sec.path); err == nil {
			id := "sec-" + sanitizeID(sec.name)
			htmlParts = append(htmlParts, fmt.Sprintf(`<li><a href="#%s">%s</a><span class="page-ref"></span></li>`, id, html.EscapeString(sec.name)))
		}
	}
	htmlParts = append(htmlParts, `</ul></div>`)
	htmlParts = append(htmlParts, `<div class="section-break"></div>`)

	for _, sec := range sections {
		if _, err := os.Stat(sec.path); err != nil {
			continue
		}

		if sec.isDir {
			files, err := os.ReadDir(sec.path)
			if err != nil {
				continue
			}
			hasContent := false
			for _, f := range files {
				if strings.HasSuffix(f.Name(), ".md") {
					content, err := os.ReadFile(filepath.Join(sec.path, f.Name()))
					if err != nil {
						continue
					}
					sectionID := "sec-" + sanitizeID(sec.name+"-"+f.Name())
					htmlResult := markdownToHTMLWithID(string(content), c.CampaignDir, sectionID, &headingCounter, c.seenImages)
					if strings.TrimSpace(htmlResult) != "" {
						htmlParts = append(htmlParts, htmlResult)
						hasContent = true
					}
				}
			}
			if hasContent {
				htmlParts = append(htmlParts, `<div class="section-break"></div>`)
			}
		} else {
			content, err := os.ReadFile(sec.path)
			if err != nil {
				continue
			}
			sectionID := "sec-" + sanitizeID(sec.name)
			htmlResult := markdownToHTMLWithID(string(content), c.CampaignDir, sectionID, &headingCounter, c.seenImages)
			if strings.TrimSpace(htmlResult) != "" {
				htmlParts = append(htmlParts, htmlResult)
			}
			htmlParts = append(htmlParts, `<div class="section-break"></div>`)
		}
	}

	htmlParts = append(htmlParts, "</body></html>")

	htmlPath := filepath.Join(c.CampaignDir, "campaign.html")
	if err := os.WriteFile(htmlPath, []byte(strings.Join(htmlParts, "\n")), 0644); err != nil {
		return "", fmt.Errorf("failed to write HTML: %w", err)
	}

	pdfPath := filepath.Join(c.CampaignDir, "campaign.pdf")
	if err := c.htmlToPDF(htmlPath, pdfPath); err != nil {
		return "", fmt.Errorf("failed to convert to PDF: %w", err)
	}

	return pdfPath, nil
}

func sanitizeID(s string) string {
	result := []rune(s)
	for i, r := range result {
		if (r < 'a' || r > 'z') && (r < 'A' || r > 'Z') && (r < '0' || r > '9') {
			result[i] = '-'
		}
	}
	return strings.ToLower(string(result))
}

func (c *Compiler) htmlToPDF(htmlPath, pdfPath string) error {
	cmd := exec.Command(c.PDFEngine,
		"--enable-local-file-access",
		"--page-size", "A4",
		"--margin-top", "15mm",
		"--margin-bottom", "15mm",
		"--margin-left", "15mm",
		"--margin-right", "15mm",
		"--print-media-type",
		"--footer-center", "[page]/[topage]",
		"--footer-font-size", "8",
		htmlPath,
		pdfPath,
	)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("wkhtmltopdf failed: %w\nOutput: %s", err, string(output))
	}
	return nil
}

var (
	boldRegex          = regexp.MustCompile(`\*\*(.+?)\*\*`)
	italicRegex        = regexp.MustCompile(`\*(.+?)\*`)
	boldAdjacentRegex  = regexp.MustCompile(`</strong>([^\s<])`)
	imageRegex         = regexp.MustCompile(`!\[([^\]]*)\]\(([^)]+)\)`)

	blockquoteRe    = regexp.MustCompile("^>\\s*(.*)")
	codeAssetRegex  = regexp.MustCompile("`assets/([\\w\\-]+\\.(svg|png|jpg|jpeg|gif|webp))`")
	sceneRegex      = regexp.MustCompile(`\[SCENE:\s*(.*?)\]`)
)

// formatInline processes bold and italic markers, ensuring no word merging after </strong>
func formatInline(text string) string {
	text = boldRegex.ReplaceAllString(text, "<strong>$1</strong>")
	text = boldAdjacentRegex.ReplaceAllString(text, "</strong>&thinsp;$1")
	return italicRegex.ReplaceAllString(text, "<em>$1</em>")
}

func markdownToHTMLWithID(md string, baseDir string, sectionID string, headingCounter *int, seenImages map[string]bool) string {
	lines := strings.Split(md, "\n")
	var out []string
	inList := false
	var paragraphLines []string

	// Table state
	inTable := false
	var tableRows []string
	var pendingTableRow string // buffered row waiting for separator confirmation

	// Blockquote state (read-aloud)
	inBlockquote := false
	var blockquoteLines []string

	// Code block state
	inCodeBlock := false
	var codeBlockLines []string

	flushCodeBlock := func() {
		if len(codeBlockLines) == 0 {
			return
		}
		code := strings.Join(codeBlockLines, "\n")
		codeBlockLines = nil
		if code == "" {
			return
		}
		escaped := html.EscapeString(code)
		out = append(out, fmt.Sprintf(`<pre class="code-block"><code>%s</code></pre>`, escaped))
	}

	flushBlockquote := func() {
		if len(blockquoteLines) == 0 {
			return
		}
		text := strings.Join(blockquoteLines, " ")
		blockquoteLines = nil
		if text == "" {
			return
		}
		escaped := html.EscapeString(text)
		escaped = formatInline(escaped)
		escaped = processImages(escaped, baseDir, seenImages)
		out = append(out, fmt.Sprintf(`<div class="read-aloud">%s</div>`, escaped))
	}

	flushParagraph := func() {
		if len(paragraphLines) == 0 {
			return
		}
		text := strings.Join(paragraphLines, " ")
		paragraphLines = nil
		if text == "" {
			return
		}
		escaped := html.EscapeString(text)
		escaped = formatInline(escaped)
		escaped = processImages(escaped, baseDir, seenImages)
		out = append(out, fmt.Sprintf("<p>%s</p>", escaped))
	}

	flushTable := func() {
		if len(tableRows) < 2 {
			// Not a valid table, treat rows as paragraphs
			for _, row := range tableRows {
				if strings.TrimSpace(row) != "" {
					escaped := html.EscapeString(strings.TrimSpace(row))
					escaped = formatInline(escaped)
					out = append(out, fmt.Sprintf("<p>%s</p>", escaped))
				}
			}
			tableRows = nil
			return
		}
		headers := parseTableRow(tableRows[0])
		alignments := parseTableAlign(tableRows[1])
		var htmlOut strings.Builder
		htmlOut.WriteString(`<table><thead><tr>`)
		for i, h := range headers {
			align := ""
			if i < len(alignments) {
				align = alignments[i]
			}
			if align != "" {
				htmlOut.WriteString(fmt.Sprintf(`<th style="text-align:%s">%s</th>`, align, h))
			} else {
				htmlOut.WriteString(fmt.Sprintf(`<th>%s</th>`, h))
			}
		}
		htmlOut.WriteString(`</tr></thead><tbody>`)
		for _, row := range tableRows[2:] {
			cells := parseTableRow(row)
			htmlOut.WriteString(`<tr>`)
			for i, cell := range cells {
				align := ""
				if i < len(alignments) {
					align = alignments[i]
				}
				cellEsc := html.EscapeString(cell)
				cellEsc = formatInline(cellEsc)
				if align != "" {
					htmlOut.WriteString(fmt.Sprintf(`<td style="text-align:%s">%s</td>`, align, cellEsc))
				} else {
					htmlOut.WriteString(fmt.Sprintf(`<td>%s</td>`, cellEsc))
				}
			}
			htmlOut.WriteString(`</tr>`)
		}
		htmlOut.WriteString(`</tbody></table>`)
		out = append(out, htmlOut.String())
		tableRows = nil
	}

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Skip horizontal rules (---, ***, ___, - - -)
		if trimmed == "---" || trimmed == "***" || trimmed == "___" || trimmed == "- - -" {
			continue
		}

		// Skip empty lines inside table
		if inTable && trimmed == "" {
			continue
		}

		// Handle scene placeholders [SCENE: description]
		if sceneMatch := sceneRegex.FindStringSubmatch(trimmed); sceneMatch != nil {
			flushParagraph()
			flushBlockquote()
			flushTable()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			sceneDesc := sceneMatch[1]
			escaped := html.EscapeString(sceneDesc)
			escaped = formatInline(escaped)
			out = append(out, fmt.Sprintf(`<div class="scene-description">🎭 %s</div>`, escaped))
			continue
		}

		// If we have a pending row and current line is a separator, start table
		if pendingTableRow != "" && isTableSeparator(trimmed) {
			inTable = true
			tableRows = append(tableRows, pendingTableRow)
			tableRows = append(tableRows, trimmed)
			pendingTableRow = ""
			continue
		}

		// If we have a pending row but current line is NOT a separator, flush pending as paragraph
		if pendingTableRow != "" && !isTableRow(trimmed) {
			paragraphLines = append(paragraphLines, pendingTableRow)
			pendingTableRow = ""
		}

		// If we're in a table and see another row, add it
		if inTable && isTableRow(trimmed) {
			tableRows = append(tableRows, trimmed)
			continue
		}

		// If we were in a table but now see non-table content, flush table
		if inTable {
			flushTable()
			inTable = false
		}

		// If line looks like a table row, buffer it (might be table start)
		if isTableRow(trimmed) && !inTable {
			pendingTableRow = trimmed
			continue
		}

		// Handle code blocks (```)
		if strings.HasPrefix(trimmed, "```") {
			if inCodeBlock {
				// End code block
				flushCodeBlock()
				inCodeBlock = false
			} else {
				// Start code block
				flushParagraph()
				flushBlockquote()
				if inList {
					out = append(out, "</ul>")
					inList = false
				}
				inCodeBlock = true
			}
			continue
		}

		// If we're inside a code block, collect lines
		if inCodeBlock {
			codeBlockLines = append(codeBlockLines, line) // Keep original line, not trimmed
			continue
		}

		// Handle blockquotes (read-aloud text)
		if bqMatch := blockquoteRe.FindStringSubmatch(trimmed); bqMatch != nil {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			inBlockquote = true
			blockquoteLines = append(blockquoteLines, bqMatch[1])
			continue
		}

		// If we were in a blockquote but now see non-blockquote content, flush it
		if inBlockquote {
			flushBlockquote()
			inBlockquote = false
		}

		// Handle headings
		if strings.HasPrefix(trimmed, "##### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "##### ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h5 id="%s">%s</h5>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "#### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "#### ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h4 id="%s">%s</h4>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "### ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "### ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h3 id="%s">%s</h3>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "## ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "## ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h2 id="%s">%s</h2>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "# ") {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			text := strings.TrimPrefix(trimmed, "# ")
			*headingCounter++
			id := sectionID + "-h" + strconv.Itoa(*headingCounter)
			out = append(out, fmt.Sprintf(`<h1 id="%s">%s</h1>`, id, html.EscapeString(text)))
		} else if strings.HasPrefix(trimmed, "- ") || strings.HasPrefix(trimmed, "* ") {
			flushParagraph()
			if !inList {
				out = append(out, "<ul>")
				inList = true
			}
			text := strings.TrimPrefix(trimmed, "- ")
			if strings.HasPrefix(trimmed, "* ") {
				text = strings.TrimPrefix(trimmed, "* ")
			}
			escaped := html.EscapeString(text)
			escaped = formatInline(escaped)
			escaped = processImages(escaped, baseDir, seenImages)
			out = append(out, fmt.Sprintf("<li>%s</li>", escaped))
		} else if trimmed == "" {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
		} else if imageRegex.MatchString(trimmed) {
			flushParagraph()
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			out = append(out, processImages(trimmed, baseDir, seenImages))
		} else {
			if inList {
				out = append(out, "</ul>")
				inList = false
			}
			paragraphLines = append(paragraphLines, trimmed)
		}
	}

	flushParagraph()
	flushTable()
	flushBlockquote()
	flushCodeBlock()
	if inList {
		out = append(out, "</ul>")
	}

	return strings.Join(out, "\n")
}

func isTableRow(line string) bool {
	return strings.HasPrefix(line, "|") && strings.HasSuffix(line, "|") && strings.Count(line, "|") >= 3
}

func isTableSeparator(line string) bool {
	if !isTableRow(line) {
		return false
	}
	inner := strings.Trim(line, "|")
	parts := strings.Split(inner, "|")
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if p[0] != '-' && p[0] != ':' {
			return false
		}
	}
	return true
}

func parseTableRow(row string) []string {
	row = strings.TrimSpace(row)
	row = strings.TrimPrefix(row, "|")
	row = strings.TrimSuffix(row, "|")
	parts := strings.Split(row, "|")
	var result []string
	for _, p := range parts {
		result = append(result, strings.TrimSpace(p))
	}
	return result
}

func parseTableAlign(row string) []string {
	cells := parseTableRow(row)
	var alignments []string
	for _, cell := range cells {
		cell = strings.TrimSpace(cell)
		leftDash := strings.HasPrefix(cell, ":")
		rightDash := strings.HasSuffix(cell, ":")
		if leftDash && rightDash {
			alignments = append(alignments, "center")
		} else if rightDash {
			alignments = append(alignments, "right")
		} else {
			alignments = append(alignments, "left")
		}
	}
	return alignments
}

func markdownToHTML(md string, baseDir string) string {
	counter := 0
	seen := make(map[string]bool)
	return markdownToHTMLWithID(md, baseDir, "content", &counter, seen)
}

func processImages(text string, baseDir string, seenImages map[string]bool) string {
	text = imageRegex.ReplaceAllStringFunc(text, func(match string) string {
		matches := imageRegex.FindStringSubmatch(match)
		if len(matches) < 3 {
			return match
		}
		alt := matches[1]
		imgPath := matches[2]

		if !filepath.IsAbs(imgPath) {
			// Strip ../ and ./ prefixes — assets are always under campaign root
			for strings.HasPrefix(imgPath, "../") {
				imgPath = strings.TrimPrefix(imgPath, "../")
			}
			for strings.HasPrefix(imgPath, "./") {
				imgPath = strings.TrimPrefix(imgPath, "./")
			}
			imgPath = filepath.Join(baseDir, imgPath)
		}

		return embedImage(imgPath, alt, baseDir, seenImages)
	})

	// Detect code-formatted asset refs: `assets/filename.ext`
	text = codeAssetRegex.ReplaceAllStringFunc(text, func(match string) string {
		matches := codeAssetRegex.FindStringSubmatch(match)
		if len(matches) < 2 {
			return match
		}
		filename := matches[1]
		imgPath := filepath.Join(baseDir, "assets", filename)
		return embedImage(imgPath, filename, baseDir, seenImages)
	})

	return text
}

func embedImage(imgPath, alt, baseDir string, seenImages map[string]bool) string {
	// Deduplicate: skip if same image path already embedded
	if seenImages[imgPath] {
		return ""
	}
	seenImages[imgPath] = true

	data, err := os.ReadFile(imgPath)
	if err != nil {
		return fmt.Sprintf(`<span class="image-missing">[Image: %s]</span>`, html.EscapeString(alt))
	}

	ext := strings.ToLower(filepath.Ext(imgPath))
	var mimeType string

	switch ext {
	case ".svg":
		// Use SVG directly - wkhtmltopdf can render SVG files with --enable-local-file-access
		// Return relative path from campaign directory
		relPath, _ := filepath.Rel(baseDir, imgPath)
		if relPath == "" {
			relPath = imgPath
		}
		return fmt.Sprintf(`<img src="%s" alt="%s" class="campaign-image"/>`, html.EscapeString(relPath), html.EscapeString(alt))
	case ".png":
		mimeType = "image/png"
	case ".jpg", ".jpeg":
		mimeType = "image/jpeg"
	case ".gif":
		mimeType = "image/gif"
	case ".webp":
		mimeType = "image/webp"
	default:
		mimeType = "image/png"
	}

	encoded := base64.StdEncoding.EncodeToString(data)
	dataURI := fmt.Sprintf("data:%s;base64,%s", mimeType, encoded)
	return fmt.Sprintf(`<img src="%s" alt="%s" class="campaign-image"/>`, dataURI, html.EscapeString(alt))
}

