package repository

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/pauvalls/grimorio/internal/domain"
)

// FilesystemCampaignRepository implements CampaignRepository using filesystem
type FilesystemCampaignRepository struct {
	baseDir string
}

// NewFilesystemCampaignRepository creates a new filesystem campaign repository
func NewFilesystemCampaignRepository(baseDir string) *FilesystemCampaignRepository {
	return &FilesystemCampaignRepository{baseDir: baseDir}
}

func (r *FilesystemCampaignRepository) campaignDir(name string) string {
	return filepath.Join(r.baseDir, name)
}

func (r *FilesystemCampaignRepository) Create(campaign *domain.Campaign) error {
	if err := campaign.Validate(); err != nil {
		return err
	}

	dir := r.campaignDir(campaign.Name)
	subdirs := []string{"acts", "npcs", "bestiary", "encounters", "maps", "assets", "characters", "quests"}
	for _, sub := range subdirs {
		if err := os.MkdirAll(filepath.Join(dir, sub), 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", sub, err)
		}
	}

	campaign.CreatedAt = time.Now()
	campaign.UpdatedAt = time.Now()

	// Save campaign manifest
	manifestPath := filepath.Join(dir, "campaign.json")
	bytes, err := json.MarshalIndent(campaign, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal campaign: %w", err)
	}
	if err := os.WriteFile(manifestPath, bytes, 0644); err != nil {
		return fmt.Errorf("failed to save campaign manifest: %w", err)
	}

	// Create README
	manifest := fmt.Sprintf("# %s\n\n**Setting:** %s\n\n**Status:** %s\n\nGenerated by Grimorio\n",
		campaign.Title, campaign.Setting, campaign.Status)
	readmePath := filepath.Join(dir, "README.md")
	if err := os.WriteFile(readmePath, []byte(manifest), 0644); err != nil {
		return fmt.Errorf("failed to write README: %w", err)
	}

	return nil
}

func (r *FilesystemCampaignRepository) Read(name string) (*domain.Campaign, error) {
	var campaign domain.Campaign
	manifestPath := filepath.Join(r.campaignDir(name), "campaign.json")
	bytes, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("campaign not found: %w", err)
	}
	if err := json.Unmarshal(bytes, &campaign); err != nil {
		return nil, fmt.Errorf("failed to unmarshal campaign: %w", err)
	}
	return &campaign, nil
}

func (r *FilesystemCampaignRepository) Update(campaign *domain.Campaign) error {
	campaign.UpdatedAt = time.Now()
	manifestPath := filepath.Join(r.campaignDir(campaign.Name), "campaign.json")
	bytes, err := json.MarshalIndent(campaign, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(manifestPath, bytes, 0644)
}

func (r *FilesystemCampaignRepository) Delete(name string) error {
	return os.RemoveAll(r.campaignDir(name))
}

func (r *FilesystemCampaignRepository) List() ([]domain.CampaignSummary, error) {
	entries, err := os.ReadDir(r.baseDir)
	if err != nil {
		if os.IsNotExist(err) {
			return []domain.CampaignSummary{}, nil
		}
		return nil, err
	}

	var summaries []domain.CampaignSummary
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		campaign, err := r.Read(entry.Name())
		if err != nil {
			continue
		}

		acts, _ := r.listFiles(entry.Name(), "acts")
		npcs, _ := r.listFiles(entry.Name(), "npcs")
		chars, _ := r.listFiles(entry.Name(), "characters")

		summaries = append(summaries, domain.CampaignSummary{
			Name:       entry.Name(),
			Title:      campaign.Title,
			Setting:    campaign.Setting,
			Status:     campaign.Status,
			Acts:       len(acts),
			NPCs:       len(npcs),
			Characters: len(chars),
			UpdatedAt:  campaign.UpdatedAt,
		})
	}
	return summaries, nil
}

func (r *FilesystemCampaignRepository) Exists(name string) bool {
	_, err := os.Stat(r.campaignDir(name))
	return err == nil
}

func (r *FilesystemCampaignRepository) listFiles(campaign, subdir string) ([]string, error) {
	dir := filepath.Join(r.campaignDir(campaign), subdir)
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return []string{}, nil
		}
		return nil, err
	}
	var files []string
	for _, entry := range entries {
		if !entry.IsDir() {
			files = append(files, entry.Name())
		}
	}
	return files, nil
}

// Ensure interface is implemented
var _ CampaignRepository = (*FilesystemCampaignRepository)(nil)
