package handlers

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pauvalls/grimorio/internal/repository"
	"github.com/pauvalls/grimorio/internal/services"
)

func setupE2ETestHandlers(tmpDir string) (*CampaignHandlers, func()) {
	campaignRepo := repository.NewMemoryCampaignRepository()
	actRepo := repository.NewMemoryActRepository()
	charRepo := repository.NewMemoryCharacterRepository()
	npcRepo := repository.NewMemoryNPCRepository()
	questRepo := repository.NewMemoryQuestRepository()
	canonRepo := repository.NewMemoryCanonRepository()
	monsterRepo := repository.NewMemoryMonsterRepository()

	campaignService := services.NewCampaignService(
		campaignRepo, actRepo, charRepo, npcRepo, questRepo, canonRepo, monsterRepo,
		tmpDir, "",
	)

	handlers := NewCampaignHandlers(campaignService)
	cleanup := func() {
		_ = os.RemoveAll(tmpDir)
	}

	return handlers, cleanup
}

func TestE2E_WotCProfessionalFormat(t *testing.T) {
	tmpDir := t.TempDir()
	handlers, cleanup := setupE2ETestHandlers(tmpDir)
	defer cleanup()

	campaignName := "wotc-test-campaign"
	campaignTitle := "WotC Test Campaign"

	// Step 1: Create campaign
	t.Log("Step 1: Creating campaign...")
	createHandler := handlers.HandleCreateCampaign()
	result, err := createHandler(context.Background(), newToolRequest("create_campaign", map[string]any{
		"name":  campaignName,
		"title": campaignTitle,
	}))
	if err != nil {
		t.Fatalf("create_campaign error: %v", err)
	}
	if result.IsError {
		t.Fatalf("create_campaign returned error: %v", result.Content)
	}
	t.Log("Campaign created successfully")

	// Step 2: Save Lore (needed for Introduction generation context)
	t.Log("Step 2: Saving Lore...")
	loreHandler := handlers.HandleSaveLore()
	loreContent := `# Lore y Ambientación

## Adventure Background

### Timeline de Eventos Previos

1. **Event 1** — Hace 1 mes — Un evento importante ocurrió
2. **Event 2** — Hace 2 semanas — Otro evento importante

### Resumen de la Storyline

La campaña trata sobre personajes que enfrentan una amenaza creciente.

## Sinopsis General

Una aventura épica para niveles 1-3.

## El Conflicto Central

### La Amenaza
Un villano misterioso amenaza la ciudad.

### Los Interesados
Varias facciones compiten por el control.

## Temas y Tono

- **Tema 1:** Sacrificio
- **Tono general:** Oscuro y misterioso`
	result, err = loreHandler(context.Background(), newToolRequest("save_lore", map[string]any{
		"campaign": campaignName,
		"content":  loreContent,
	}))
	if err != nil {
		t.Fatalf("save_lore error: %v", err)
	}
	if result.IsError {
		t.Fatalf("save_lore returned error: %v", result.Content)
	}
	t.Log("Lore saved successfully")

	// Step 3: Save Introduction (NEW WotC feature)
	t.Log("Step 3: Saving Introduction (NEW WotC feature)...")
	introHandler := handlers.HandleSaveIntroduction()
	introContent := `# Introduction

## Foreword

Esta aventura fue diseñada para proporcionar una experiencia inolvidable a tu mesa de D&D.

---

## Story Overview

> **"En las sombras de la ciudad, algo antiguo despierta. Los personajes se encuentran en el centro de un misterio que cambiará sus vidas para siempre."**

---

## Adventure Background

### Before the Adventure

1. **El Despertar** — Hace 1 mes — Una presencia antigua comenzó a manifestarse
2. **Las Señales** — Hace 2 semanas — Los ciudadanos reportaron visiones extrañas
3. **La Desaparición** — Hace 3 días — Varios habitantes desaparecieron sin dejar rastro

---

## Running the Adventure

### Abbreviations and Conventions

| Abbreviation | Meaning |
|--------------|---------|
| **PJs** | Personajes Jugadores |
| **DM** | Dungeon Master |
| **NPC** | Personaje No Jugador |

### Read-Aloud Text

> *Text in these block quotes is meant to be read aloud to the players exactly as written.*

---

## Adventure Flowchart

*See the campaign flowchart auto-generated by the compiler.*

---

## Character Creation Guidelines

### Starting Level
Characters begin at **level 1**.

### Recommended Backgrounds
- **Soldier:** Para personajes con experiencia en combate
- **Sage:** Para personajes con conocimiento arcano`
	result, err = introHandler(context.Background(), newToolRequest("save_introduction", map[string]any{
		"campaign": campaignName,
		"content":  introContent,
	}))
	if err != nil {
		t.Fatalf("save_introduction error: %v", err)
	}
	if result.IsError {
		t.Fatalf("save_introduction returned error: %v", result.Content)
	}
	t.Log("Introduction saved successfully (NEW WotC feature)")

	// Step 4: Save Setting Guide (NEW WotC feature)
	t.Log("Step 4: Saving Setting Guide (NEW WotC feature)...")
	sgHandler := handlers.HandleSaveSettingGuide()
	sgContent := `# Setting Guide
*DM-only — contains spoilers*

---

## Geography

### Major Locations

#### La Ciudad Antigua
- **Type:** Ciudad
- **Population:** ~10,000
- **Government:** Consejo de Magistrate
- **Description:** Una ciudad construida sobre ruinas antiguas, donde la niebla nunca se disipa completamente.

---

## History

### Recent Events (Últimos 50 años)

1. **La Fundación** — Hace 200 años — La ciudad fue fundada sobre las ruinas de una civilización perdida
2. **El Gran Incendio** — Hace 50 años — Un incendio destruyó gran parte de la ciudad vieja
3. **El Retorno** — Hace 1 mes — Los eventos actuales comienzan

---

## Factions

### Los Susurradores
- **Alignment:** Neutral Evil
- **Leader:** Unknown
- **Goals:** Despertar algo antiguo y poderoso
- **Secret:** Son controlados por una entidad extra-planar

---

## Secrets and Lies

### What Nobody Knows
La verdadera amenaza no viene de esta dimensión.`
	result, err = sgHandler(context.Background(), newToolRequest("save_setting_guide", map[string]any{
		"campaign": campaignName,
		"content":  sgContent,
	}))
	if err != nil {
		t.Fatalf("save_setting_guide error: %v", err)
	}
	if result.IsError {
		t.Fatalf("save_setting_guide returned error: %v", result.Content)
	}
	t.Log("Setting Guide saved successfully (NEW WotC feature)")

	// Step 5: Save NPCs
	t.Log("Step 5: Saving NPCs...")
	npcHandler := handlers.HandleSaveNPCs()
	npcContent := `# NPCs and Factions

## Major NPCs

### Mastro Aldric
*NG male Chondathan human fighter*

Un viejo soldado que ahora trabaja como herrero. Conoce los secretos de la ciudad vieja.

**Stats:**
- AC: 18 | HP: 45 | Speed: 30 ft.
- STR: 16 (+3) | DEX: 14 (+2) | CON: 15 (+2)
- INT: 10 (+0) | WIS: 13 (+1) | CHA: 11 (+0)

**Equipment:** Longsword, Shield, Chain Mail`
	_, err = npcHandler(context.Background(), newToolRequest("save_npcs", map[string]any{
		"campaign": campaignName,
		"content":  npcContent,
	}))
	if err != nil {
		t.Fatalf("save_npcs error: %v", err)
	}
	t.Log("NPCs saved successfully")

	// Step 6: Save Bestiary
	t.Log("Step 6: Saving Bestiary...")
	bestiaryHandler := handlers.HandleSaveBestiary()
	bestiaryContent := `# Bestiary

## Monsters

### Whispering Specter
*Medium undead, chaotic evil*

**AC** 12 | **HP** 22 | **Speed** 0 ft., fly 40 ft.

| STR | DEX | CON | INT | WIS | CHA |
|-----|-----|-----|-----|-----|-----|
| 6 (-2) | 14 (+2) | 11 (+0) | 12 (+1) | 11 (+0) | 14 (+2) |

**Skills** Stealth +4 | **Senses** darkvision 60 ft. | **Languages** understands languages spoken in life
**Challenge** 2 (450 XP)

**Silent Step.** The specter makes no sound when moving.

**Actions**
**Life Drain.** *Melee:* +4 to hit, 5 ft., one creature. *Hit:* 7 (2d6) necrotic damage. Target must succeed DC 10 CON save or have HP max reduced by same amount.`
	_, err = bestiaryHandler(context.Background(), newToolRequest("save_bestiary", map[string]any{
		"campaign": campaignName,
		"content":  bestiaryContent,
	}))
	if err != nil {
		t.Fatalf("save_bestiary error: %v", err)
	}
	t.Log("Bestiary saved successfully")

	// Step 7: Save Appendices (NEW WotC feature)
	t.Log("Step 7: Saving Appendices (NEW WotC feature)...")
	appHandler := handlers.HandleSaveAppendices()
	appContent := `# Appendices

---

## Appendix A: Magic Items

### Llave de Plata
*Uncommon, Wondrous Item*

Una llave de plata que brilla con luz propia. Abre cualquier cerradura de plata o inferior.

**Activation:** Click the key while holding it.

---

## Appendix B: NPCs and Monsters

#### Mastro Aldric
*NG male Chondathan human fighter*

**AC** 18 | **HP** 45 | **Speed** 30 ft.

| STR | DEX | CON | INT | WIS | CHA |
|-----|-----|-----|-----|-----|-----|
| 16 (+3) | 14 (+2) | 15 (+2) | 10 (+0) | 13 (+1) | 11 (+0) |

**Skills** Athletics +5, Perception +3 | **Senses** passive Perception 13
**Challenge** 3 (700 XP)

**Actions**
**Longsword.** *Melee Weapon Attack:* +5 to hit, reach 5 ft., one target. *Hit:* 10 (2d8 + 3) slashing damage.

---

## Appendix C: Handouts

### Handout 1: Carta Misteriosa

*Los jugadores encuentran esta carta en el cuerpo de un NPC muerto:*

> "El consejo se reúne cuando la luna atraviesa las nubes. Busca la verdad en las sombras."

---

## Appendix E: Reference Tables

### Random Encounters

| d6 | Encounter | Location |
|----|-----------|----------|
| 1 | 2d4 Whispering Specters | Ciudad Vieja |
| 2 | 1d6 Bandidos | Callejones |
| 3 | Mastro Aldric | Herrería |
| 4 | Ninguno | — |
| 5 | 1d4 Rats | Sótanos |
| 6 | Mercader Ambiguo | Mercado |

---

*End of Appendices*`
	result, err = appHandler(context.Background(), newToolRequest("save_appendices", map[string]any{
		"campaign": campaignName,
		"content":  appContent,
	}))
	if err != nil {
		t.Fatalf("save_appendices error: %v", err)
	}
	if result.IsError {
		t.Fatalf("save_appendices returned error: %v", result.Content)
	}
	t.Log("Appendices saved successfully (NEW WotC feature)")

	// Step 8: Verify files exist
	t.Log("Step 8: Verifying files exist...")
	campaignPath := filepath.Join(tmpDir, campaignName)
	files := []string{
		"introduction.md",
		"setting-guide.md",
		"appendices.md",
		"lore.md",
	}
	for _, f := range files {
		path := filepath.Join(campaignPath, f)
		if _, err := os.Stat(path); err != nil {
			t.Errorf("Expected file not found: %s", path)
		} else {
			t.Logf("  ✓ %s exists", f)
		}
	}

	// Step 9: Compile PDF
	t.Log("Step 9: Compiling PDF...")
	compileHandler := handlers.HandleCompilePDF()
	result, err = compileHandler(context.Background(), newToolRequest("compile_pdf", map[string]any{
		"campaign": campaignName,
		"title":    campaignTitle,
	}))
	if err != nil {
		t.Fatalf("compile_pdf error: %v", err)
	}

	// Note: PDF compilation may fail if no PDF engine is available
	// but the handler should not panic
	if result.IsError {
		t.Logf("PDF compilation note: %v", result.Content)
	} else {
		t.Log("PDF compiled (or command sent)")

		// Verify HTML was generated (even if PDF fails, HTML should exist)
		htmlPath := filepath.Join(campaignPath, "campaign.html")
		if _, err := os.Stat(htmlPath); err == nil {
			t.Log("  ✓ campaign.html generated")

			// Verify the new sections are in the HTML
			htmlContent, _ := os.ReadFile(htmlPath)
			htmlStr := string(htmlContent)

			sections := []struct {
				name     string
				search   string
			}{
				{"Introduction section", "Introduction"},
				{"Setting Guide section", "Setting Guide"},
				{"Setting Guide DM-only", "DM-only"},
				{"Appendices section", "Appendices"},
				{"Appendix A Magic Items", "Magic Items"},
				{"Appendix B NPCs", "Mastro Aldric"},
				{"Appendix C Handouts", "Handouts"},
				{"Foreword", "Foreword"},
				{"Story Overview", "Story Overview"},
				{"Adventure Background", "Adventure Background"},
				{"Geography", "Geography"},
				{"Factions", "Factions"},
				{"Secrets and Lies", "Secrets and Lies"},
			}

			for _, sec := range sections {
				if strings.Contains(htmlStr, sec.search) {
					t.Logf("  ✓ '%s' found in HTML", sec.name)
				} else {
					t.Errorf("  ✗ '%s' NOT found in HTML", sec.name)
				}
			}
		} else {
			t.Log("  Note: campaign.html not found (no PDF engine may be available)")
		}
	}

	// Step 10: Get templates
	t.Log("Step 10: Testing GetTemplate for new types...")
	templateHandler := handlers.HandleGetTemplate()

	newTemplates := []string{"introduction", "setting-guide", "appendices"}
	for _, tmplType := range newTemplates {
		result, err := templateHandler(context.Background(), newToolRequest("get_template", map[string]any{
			"type": tmplType,
		}))
		if err != nil {
			t.Errorf("get_template(%s) error: %v", tmplType, err)
			continue
		}
		if result.IsError {
			t.Errorf("get_template(%s) returned error: %v", tmplType, result.Content)
			continue
		}
		t.Logf("  ✓ get_template(%s) succeeded", tmplType)
	}

	t.Log("\n=== E2E WotC Professional Format Test COMPLETE ===")
	t.Log("New features verified:")
	t.Log("  - Introduction (Foreword, Story Overview, Adventure Background, Running the Adventure)")
	t.Log("  - Setting Guide (DM-only, Geography, History, Factions, Secrets)")
	t.Log("  - Appendices (Magic Items, NPCs/Monsters, Handouts, Reference Tables)")
}

func TestE2E_ChapterSequentialFlow(t *testing.T) {
	tmpDir := t.TempDir()
	handlers, cleanup := setupE2ETestHandlers(tmpDir)
	defer cleanup()

	campaignName := "chapter-e2e-test"
	campaignTitle := "Chapter E2E Test Campaign"

	// Step 1: Create campaign
	t.Log("Step 1: Creating campaign...")
	createHandler := handlers.HandleCreateCampaign()
	result, err := createHandler(context.Background(), newToolRequest("create_campaign", map[string]any{
		"name":  campaignName,
		"title": campaignTitle,
	}))
	if err != nil {
		t.Fatalf("create_campaign error: %v", err)
	}
	if result.IsError {
		t.Fatalf("create_campaign returned error: %v", result.Content)
	}

	// Step 2: Save Introduction
	t.Log("Step 2: Saving Introduction...")
	introHandler := handlers.HandleSaveIntroduction()
	_, err = introHandler(context.Background(), newToolRequest("save_introduction", map[string]any{
		"campaign": campaignName,
		"content":  "# Introduction\n\nTest campaign.",
	}))
	if err != nil {
		t.Fatalf("save_introduction error: %v", err)
	}

	// Step 3: Save Lore
	t.Log("Step 3: Saving Lore...")
	loreHandler := handlers.HandleSaveLore()
	_, err = loreHandler(context.Background(), newToolRequest("save_lore", map[string]any{
		"campaign": campaignName,
		"content":  "# Lore\n\nTest lore.",
	}))
	if err != nil {
		t.Fatalf("save_lore error: %v", err)
	}

	// Step 4: Save Chapter 1 (NEW: self-contained chapter)
	t.Log("Step 4: Saving Chapter 1 via save_chapter...")
	chapterHandler := handlers.HandleSaveChapter()
	chapterContent := `# Capítulo 1: El Comienzo

## Apertura Narrativa

Los héroes llegan al pueblo.

## NPCs en este Capítulo

### Aldeano Mayor
*Neutral humano*

Un viejo líder del pueblo.

## Encuentros

### Encuentro 1: Emboscada
*Dificultad: Medium*

Los bandidos atacan desde las sombras.

**Monstruos:**
- 3x Bandido

**Recompensas:**
- 100 XP

## Áreas

### Área 1: Entrada del Pueblo

> Los jugadores ven el pueblo desde la colina.

La entrada está custodiada por guardias.

**Características:**
- **Muralla:** Madera reforzada

**Tesoro:**
- Monedas de cobre (10 gp)

**Desarrollo:** Los guardias permiten el paso si los PJs son amistosos.

**Ganchos:**
- El mercader les ofrece una quest
- Un niño les pide ayuda

### Área 2: La Taberna

> Humo y risas salen de la taberna.

Un lugar acogedor para descansar.

**Características:**
- **Barra:** El tabernero conoce rumores

**Tesoro:**
- Poción de curación (50 gp)

**Desarrollo:** El tabernero menciona la cueva misteriosa.

**Ganchos:**
- Un mensajero busca a los héroes
- Un duelo amistoso ofrece recompensa

## Consecuencias y Transición

El pueblo queda a salvo.

**Gancho al siguiente capítulo:** Una carta llega con noticias oscuras.
`

	result, err = chapterHandler(context.Background(), newToolRequest("save_chapter", map[string]any{
		"campaign":       campaignName,
		"chapter_number": float64(1),
		"title":          "El Comienzo",
		"content":        chapterContent,
	}))
	if err != nil {
		t.Fatalf("save_chapter error: %v", err)
	}
	if result.IsError {
		t.Fatalf("save_chapter returned error: %v", result.Content)
	}
	t.Log("Chapter 1 saved successfully")

	// Step 5: Verify chapter file exists
	t.Log("Step 5: Verifying chapter file...")
	chapterPath := filepath.Join(tmpDir, campaignName, "chapters", "chapter_01.md")
	if _, err := os.Stat(chapterPath); os.IsNotExist(err) {
		t.Fatalf("Chapter file not found: %s", chapterPath)
	}
	t.Logf("  ✓ chapter_01.md exists")

	// Step 6: Save Bestiary (needed for creature references)
	t.Log("Step 6: Saving Bestiary...")
	bestiaryHandler := handlers.HandleSaveBestiary()
	bestiaryContent := `# Bestiary

## Bandido
*Medium humanoid*

**AC** 12 | **HP** 11
`
	_, err = bestiaryHandler(context.Background(), newToolRequest("save_bestiary", map[string]any{
		"campaign": campaignName,
		"content":  bestiaryContent,
	}))
	if err != nil {
		t.Fatalf("save_bestiary error: %v", err)
	}

	// Step 7: Save Appendices
	t.Log("Step 7: Saving Appendices...")
	appendixHandler := handlers.HandleSaveAppendices()
	_, err = appendixHandler(context.Background(), newToolRequest("save_appendices", map[string]any{
		"campaign": campaignName,
		"content":  "# Appendices\n\nTest appendices.",
	}))
	if err != nil {
		t.Fatalf("save_appendices error: %v", err)
	}

	// Step 8: Compile PDF
	t.Log("Step 8: Compiling PDF...")
	compileHandler := handlers.HandleCompilePDF()
	result, err = compileHandler(context.Background(), newToolRequest("compile_pdf", map[string]any{
		"campaign": campaignName,
		"title":    campaignTitle,
	}))
	if err != nil {
		t.Fatalf("compile_pdf error: %v", err)
	}

	if result.IsError {
		t.Logf("PDF compilation note: %v", result.Content)
	} else {
		t.Log("PDF compiled successfully")
	}

	// Verify HTML was generated and contains chapter content
	htmlPath := filepath.Join(tmpDir, campaignName, "campaign.html")
	if _, err := os.Stat(htmlPath); err == nil {
		htmlContent, _ := os.ReadFile(htmlPath)
		htmlStr := string(htmlContent)

		checks := []struct {
			name   string
			search string
		}{
			{"Chapter title", "Capítulo 1"},
			{"Area 1", "Área 1"},
			{"Area 2", "Área 2"},
			{"NPC section", "Aldeano Mayor"},
			{"Encounter section", "Emboscada"},
			{"Consequences", "Consecuencias"},
		}

		for _, check := range checks {
			if strings.Contains(htmlStr, check.search) {
				t.Logf("  ✓ '%s' found in HTML", check.name)
			} else {
				t.Errorf("  ✗ '%s' NOT found in HTML", check.name)
			}
		}
	} else {
		t.Log("  Note: campaign.html not found (no PDF engine may be available)")
	}

	// Step 9: Verify chapters/ directory is used (not areas/)
	areasDir := filepath.Join(tmpDir, campaignName, "areas")
	if _, err := os.Stat(areasDir); os.IsNotExist(err) {
		t.Log("  ✓ No areas/ directory (using chapters/ structure)")
	} else {
		t.Log("  Note: areas/ directory exists (may be from campaign creation)")
	}

	t.Log("\n=== E2E Chapter-Sequential Flow Test COMPLETE ===")
}